### ISSUE TITLE
Nothing on 8080 or

### ISSUE THREAD

**Issue by toolshc** [kasperisager/php-dockerized#19]
Hi:

   phpstack concept is great, I would like to use it.

   My OS is Ubuntu, I used DOCKER_HOST

    export DOCKER_HOST=tcp://192.168.33.10:2375

After "installation" process, everything seems to be up and running, but...
There is nothing at http://192.168.33.10:8080
Message at http://192.168.33.10:2375 is 'Page not found'

   After vagrant halt, and up again; it goes even worse
docker-compose up
Recreating ..._shipyard_1...
Cannot start container ...d5db: exec: "/bin/echo": stat /bin/echo: no such file or directory

Could you give me a hint to solve this problem?

Thanks
Best Regards!

**Comment by kasperisager** [comment]
Shipyard has been removed from the project as it was causing more harm than good.
