### ISSUE TITLE
php5-fpm exiting 

### ISSUE THREAD

**Issue by PabloC** [kasperisager/php-dockerized#20]
Any idea why php5-fpm is exiting?

front_1 | 2015-06-02 22:35:17,899 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
front_1 | 2015-06-02 22:35:17,899 INFO success: hhvm-fastcgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
front_1 | 2015-06-02 22:35:17,901 INFO spawned: 'php5-fpm' with pid 21
front_1 | 2015-06-02 22:35:17,938 INFO exited: php5-fpm (exit status 70; not expected)
front_1 | 2015-06-02 22:35:17,938 CRIT reaped unknown pid 23)
front_1 | 2015-06-02 22:35:19,942 INFO spawned: 'php5-fpm' with pid 24
front_1 | 2015-06-02 22:35:19,978 INFO exited: php5-fpm (exit status 70; not expected)
front_1 | 2015-06-02 22:35:19,978 CRIT reaped unknown pid 26)
front_1 | 2015-06-02 22:35:22,985 INFO spawned: 'php5-fpm' with pid 27
front_1 | 2015-06-02 22:35:23,021 INFO exited: php5-fpm (exit status 70; not expected)
front_1 | 2015-06-02 22:35:23,021 CRIT reaped unknown pid 29)
front_1 | 2015-06-02 22:35:24,023 INFO gave up: php5-fpm entered FATAL state, too many start retries too quickly

**Comment by joshporter** [comment]
+1 same issue for me too.

```
front_1         | /usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
front_1         |   'Supervisord is running as root and it is searching '
front_1         | 2015-06-11 15:53:31,593 CRIT Supervisor running as root (no user in config file)
front_1         | 2015-06-11 15:53:31,593 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
front_1         | 2015-06-11 15:53:31,635 INFO RPC interface 'supervisor' initialized
front_1         | 2015-06-11 15:53:31,635 CRIT Server 'unix_http_server' running without any HTTP authentication checking
front_1         | 2015-06-11 15:53:31,636 INFO supervisord started with pid 1
front_1         | 2015-06-11 15:53:32,638 INFO spawned: 'nginx' with pid 11
front_1         | 2015-06-11 15:53:32,640 INFO spawned: 'hhvm-fastcgi' with pid 12
front_1         | 2015-06-11 15:53:32,644 INFO spawned: 'php5-fpm' with pid 13
front_1         | 2015-06-11 15:53:33,039 INFO exited: php5-fpm (exit status 0; not expected)
front_1         | 2015-06-11 15:53:34,047 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
front_1         | 2015-06-11 15:53:34,047 INFO success: hhvm-fastcgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
front_1         | 2015-06-11 15:53:34,053 INFO spawned: 'php5-fpm' with pid 24
front_1         | 2015-06-11 15:53:34,190 INFO exited: php5-fpm (exit status 70; not expected)
front_1         | 2015-06-11 15:53:34,192 CRIT reaped unknown pid 26)
front_1         | 2015-06-11 15:53:36,197 INFO spawned: 'php5-fpm' with pid 27
front_1         | 2015-06-11 15:53:36,227 INFO exited: php5-fpm (exit status 70; not expected)
front_1         | 2015-06-11 15:53:36,230 CRIT reaped unknown pid 29)
front_1         | 2015-06-11 15:53:39,235 INFO spawned: 'php5-fpm' with pid 30
front_1         | 2015-06-11 15:53:39,268 INFO exited: php5-fpm (exit status 70; not expected)
front_1         | 2015-06-11 15:53:39,271 INFO gave up: php5-fpm entered FATAL state, too many start retries too quickly
front_1         | 2015-06-11 15:53:39,271 CRIT reaped unknown pid 32)
```

**Comment by Dareen** [comment]
+1

**Comment by vitosans** [comment]
The problem is php5-fpm is running in daemon mode. Which supervisor does not like. 

I added the following to my Dockerfile: 

RUN sed -i 's/;daemonize = yes/daemonize = no/g' /etc/php5/fpm/php-fpm.conf

And also my supervisord entry for php5-fpm looks like this:

[program:php5-fpm]
command=/usr/sbin/php5-fpm
priority=999
username=www-data
autostart=true
autorestart=unexpected
redirect_stderr=true
exitcodes=0

Let me know if these fixes it.

**Comment by kasperisager** [comment]
Just got around to taking a look at this; let me know if 66c5981 fixes the issue.
