### ISSUE TITLE
Shipyard not showing anything

### ISSUE THREAD

**Issue by hchoudhrydw** [kasperisager/php-dockerized#21]
I have cloned this repo, when I connect to port 80 I can see the phpinfo page but when I use 8080 I can see the shipyard UI but no containers are displayed and nothing in the dashboard!

**Comment by kasperisager** [comment]
As per the instructions: 

> Once everything is up and running, you can access Shipyard at http://<IP>:8080. The default user credentials are admin:shipyard. Once logged in, you will need to add an engine with an address of http://<IP>:2375 to see the local containers.
