### ISSUE TITLE
HHVM NginX 502 Gateway Error

### ISSUE THREAD

**Issue by argenisleon** [kasperisager/php-dockerized#25]
Hi,

When I change the default.vhost from php-fpm to hhvm I get a 502 Gateway Error. Any help?

**Comment by daper** [comment]
hello, same error, i'm investigating it... Any help would be great :)

**Comment by daper** [comment]
Review in conf/supervisord.conf the socket file of hhvm... That solved me.

**Comment by daper** [comment]
I made a pr with this changes.
