### ISSUE TITLE
Question: How can I turn off allow_url_fopen or load any setting in php.ini

### ISSUE THREAD

**Issue by dimitrismitsis** [kasperisager/php-dockerized#32]
Hi,

It seems that I can't load the settings placed in conf/php.ini

This is more of a question because I'm probably doing something wrong

I've changed the setting, removed all images, restarted all services but I'm unable to apply the change.

Thanks for your answer in advance!

**Comment by sgrover** [comment]
The php.ini is copied via the Dockerfile.  That means if you make a change to the .ini file you'll have to re-apply the Dockerfile.  That means rebuilding your image.  Do any appropriate backups needed (should be minimal with this setup unless you are doing stuff directly within the container that needs to be saved...).  Once you've done that then do the following:
```
docker-compose stop
docker-compose build
docker-compose start
``` 
That should get any new php.ini changes applied.
(Disclaimer I'm not an expert with Docker so may not have this right, but I do a similar process with a dockerized Magento environment when needed, with success...)

**Comment by kasperisager** [comment]
Rebuilding the container is indeed the solution :+1:
