### ISSUE TITLE
Not working collectstatic

### ISSUE THREAD

**Issue by tanrax** [kasperisager/php-dockerized#34]
I did not see the Admin styles. So I execute:
```
docker-compose run web /usr/local/bin/python manage.py collectstatic
```
But it returns:
```
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
```

**Comment by kasperisager** [comment]
What exactly does this have to do with php-dockerized?

**Comment by tanrax** [comment]
Sorry, wrong repository :package :P
I take this opportunity to congratulate you for php-dockerized. I use it often :D

**Comment by kasperisager** [comment]
Ah, no worries! Thanks a ton by the way :tada:
