### ISSUE TITLE
did you consider database volumes

### ISSUE THREAD

**Issue by Amin-z** [kasperisager/php-dockerized#35]
Thanks a lot for your work, worked out of the box. I was just wondering why it doesn't  have volumes for DB so that MySQL or Mongo data is persistent

**Comment by kasperisager** [comment]
Data is already persisted within the MySQL and Mongo containers and I saw no need to use data-only containers in a dev environment.

**Comment by Amin-z** [comment]
I see ! didn't know data is persisted on MySQL/Mongodb, thanks a lot
