### ISSUE TITLE
How can I run commands on the front service?

### ISSUE THREAD

**Issue by Mattnmoore** [kasperisager/php-dockerized#37]
First of all, this is the most useful setup I've been able to find for dockerized PHP, so thank you!

I'm setting up a Laravel project, and I'm wondering if there's a way to easily run commands on the `front` service through the terminal. Since supervisor is the entry point, I'm unable to start a bash shell or run composer or anything like that.

**Comment by Mattnmoore** [comment]
I found a temporary solution, not sure if this is the right way to do it, but I got rid of the `ENTRYPOINT` and changed it to a `CMD`. Now I can run commands like `composer` and `artisan` through `docker-compose`.

Closing unless there's a better way to accomplish this.

**Comment by kasperisager** [comment]
Perhaps see: https://github.com/kasperisager/php-dockerized/pull/36#issuecomment-171967654
