### ISSUE TITLE
Can't connect to mysql: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'

### ISSUE THREAD

**Issue by iamthom** [kasperisager/php-dockerized#43]
Hi, I'm trying your repo, and it is very great!

Well, got an issue with mysql. I could access this `mysql -h localhost -P 3306 --protocol=tcp -uroot -p`. But, my PHP app, cant connect to the database and throw error `Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock'`

How can I solve this?

**Comment by kasperisager** [comment]
Check out https://github.com/kasperisager/php-dockerized/issues/11#issuecomment-68594425

**Comment by iamthom** [comment]
You rocks! Many thanks! It works now.

**Comment by kasperisager** [comment]
Beauty, no problem!
