### ISSUE TITLE
[ASK] How do I apply some custom configuration?

### ISSUE THREAD

**Issue by iamthom** [kasperisager/php-dockerized#44]
Hello, I'd like to ask about how do I add my configuration, such as my.cnf, .bashrc etc? I believe by editing it inside the container is not the best practice, even though that's what I did for now.

Thank you in advance.

**Comment by kasperisager** [comment]
You can add files to the container from within the Dockerfile as seen here: https://github.com/kasperisager/php-dockerized/blob/master/Dockerfile#L50-L53

**Comment by iamthom** [comment]
Hi @kasperisager, thank you for the response. Now I wonder about applying changes in Dockerfile (rebuild it) without losing data or maybe there's something like 'hot reloading' to just reload configuration. What I believe is, by rebuilding it, it would make start over a fresh container, including the data. For example, I have a running container and later I only need to do a little change in php.ini which I've forgotten.

Is there any way to not lose data, such as mysql databases on rebuil? Or should I consider to move mysql data to a persistent folder?

**Comment by kasperisager** [comment]
Persistent data is rather finicky to manage in Docker. Take a look at this for more info: https://docs.docker.com/engine/userguide/containers/dockervolumes/
