### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jeffekg** [kasperisager/php-dockerized#47]
When running docker-compose up, getting these errors:

`#docker-compose up
Creating devstack_mysql_1
Building front
Step 1 : FROM nginx
 ---> 0d409d33b27e
Step 2 : RUN rm -f /etc/nginx/conf.d/*
 ---> Using cache
 ---> b2eb6f3730ce
Step 3 : RUN apt-get update && apt-get install -my   supervisor   curl   wget   php5-curl   php5-fpm   php5-gd   php5-memcached   php5-mysql   php5-mcrypt   php5-sqlite   php5-xdebug   php-apc
 ---> Running in 380a58213fb9
Err http://httpredir.debian.org jessie InRelease
  
Err http://httpredir.debian.org jessie-updates InRelease
  
Err http://httpredir.debian.org jessie Release.gpg
  Could not resolve 'httpredir.debian.org'
Err http://httpredir.debian.org jessie-updates Release.gpg
  Could not resolve 'httpredir.debian.org'
Err http://nginx.org jessie InRelease
  
Err http://nginx.org jessie Release.gpg
  Could not resolve 'nginx.org'
Err http://security.debian.org jessie/updates InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Reading package lists...
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://nginx.org/packages/mainline/debian/dists/jessie/InRelease  

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://nginx.org/packages/mainline/debian/dists/jessie/Release.gpg  Could not resolve 'nginx.org'

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package php5-fpm is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package supervisor
E: Unable to locate package curl
E: Unable to locate package wget
E: Unable to locate package php5-curl
E: Package 'php5-fpm' has no installation candidate
E: Unable to locate package php5-gd
E: Unable to locate package php5-memcached
E: Unable to locate package php5-mysql
E: Unable to locate package php5-mcrypt
E: Unable to locate package php5-sqlite
E: Unable to locate package php5-xdebug
E: Unable to locate package php-apc
ERROR: Service 'front' failed to build: The command '/bin/sh -c apt-get update && apt-get install -my   supervisor   curl   wget   php5-curl   php5-fpm   php5-gd   php5-memcached   php5-mysql   php5-mcrypt   php5-sqlite   php5-xdebug   php-apc' returned a non-zero code: 100`

**Comment by kasperisager** [comment]
Either the Debian source is down or your box isn't connected to the internet. Have you tried again since opening the issue?

**Comment by jeffekg** [comment]
Yes the container had no connection.  I had to edit /etc/NetworkManager/NetworkManager.conf and comment out "dns=dnsmasq" to get connections working
