### ISSUE TITLE
How to use supervisor php5-fpm logging?

### ISSUE THREAD

**Issue by jaapen** [kasperisager/php-dockerized#49]
Do I need to activate this somewhere? The files php5-fpm-stderr + php5-fpm-stdout are always empty.

**Comment by edwardmp** [comment]
same issue here

**Comment by kasperisager** [comment]
I don't remember ever seeing anything in the php5-fpm log, but the other logs work just fine. Are you maybe looking for the Nginx logs instead?

**Comment by jaapen** [comment]
I thought the standard PHP errors would be shown in the php5-fpm log file. Am I wrong?

**Comment by kasperisager** [comment]
Ah! Those are shown in the Nginx log 👍

**Comment by jaapen** [comment]
Thx 👍
