### ISSUE TITLE
Mysql configuration

### ISSUE THREAD

**Issue by iamthom** [kasperisager/php-dockerized#50]
Hey, back again with a question. How should I add my.cnf custom configuration? For example I need set max_allowed_packet to 150M. I did this:

created conf/mysql/custom.cnf

> [mysqld]
> max_allowed_packet=150M

and in docker-compose.yml

> mysql:
>   # some lines
>    volumes:
>     - ./conf/mysql:/etc/mysql/conf.d

but on `docker-compose build mysql`, it said, `mysql uses an image, skipping`. Why was that?

Thank you for the help.

**Comment by kasperisager** [comment]
I'm not entirely sure what's up with that. Have you tried removing the `mysql` service entirely and then rebuilding it?

**Comment by iamthom** [comment]
Hmm.. I ended up by using another image, based on mysql : `alterway/mysql:5.5`. It allows me to pass some envs. I forgot to mention, if I was using mysql:5.5. For now, it works. But still wonder why my prev way can't be used.. Wonder about this too, https://github.com/docker-library/mysql/blob/dbb83a94ee0a994651dd430d27caeac652cf9e78/5.5/Dockerfile#L64

**Comment by iamthom** [comment]
ok, lemme move this to solved then..
