### ISSUE TITLE
How can i place multiple projects in the www folder

### ISSUE THREAD

**Issue by raheelkhan** [kasperisager/php-dockerized#51]
I have made a new folder inside the `www` folder. But when i access `localhost/myproject`, It still goes to the default/index.php page.

**Comment by kasperisager** [comment]
You will need to define a server block for each site in the `www` directory. You can do this by copying the `default.vhost` file in the `sites` directory and then tweaking the config for your new site. You will likely only need to change the `server_name` and `root` properties.

**Comment by raheelkhan** [comment]
Yeah it worked thanks
