### ISSUE TITLE
gettext support

### ISSUE THREAD

**Issue by tugh** [kasperisager/php-dockerized#53]
Hi this project is awesome, and I love it.

But I have problem when adding gettext to the front container. Could you please add gettext to the container? 

Thanks in advance.

**Comment by kasperisager** [comment]
Glad you like the project! What seems to be the problem? I can definitely lend a hand in solving it, but as the front container is already rather bloated as is I don't wan't to bloat it further with arbitrary packages.

**Comment by tugh** [comment]
ok, thanks. I forked and added gettext support. Really good project bro.

**Comment by kasperisager** [comment]
Neat, and thanks a ton! 💯
