### ISSUE TITLE
docker-compose up stuck at step 3/18.

### ISSUE THREAD

**Issue by existenceE** [kasperisager/php-dockerized#54]
![image](https://user-images.githubusercontent.com/4418790/29037168-180c7c98-7bd5-11e7-82d3-441e7081a0ee.png)

I'm not sure how to deal with this .
Could anyone can help me ? 
Thanks a lot.

**Comment by khs1994** [comment]
在 Dockerfile 中替换为APT国内源，和实际操作系统 Debian 一样的添加方法。

**Comment by khs1994** [comment]
我粗略看了下，这个 Dockerfile 不是很好。把 nginx 和 PHP 放到了一个容器中，不建议这么做。

**Comment by kasperisager** [comment]
Agreed, they should be separated into two.

**Comment by kasperisager** [comment]
This might be related to #55 and the fact that `master` is failing as well (https://travis-ci.org/kasperisager/php-dockerized).
