### ISSUE TITLE
Win 10 issues

### ISSUE THREAD

**Issue by sonicviz** [kasperisager/php-dockerized#55]
....
Get:4 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [6499 B]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:9 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2479 B]
Get:10 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [9500 kB]
Fetched 10.1 MB in 2s (3374 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package php5-gd is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5-mcrypt is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5-mysql is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5-sqlite is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5-curl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php-apc is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5-curl' has no installation candidate
E: Unable to locate package php5-fpm
E: Package 'php5-gd' has no installation candidate
E: Unable to locate package php5-memcached
E: Package 'php5-mysql' has no installation candidate
E: Package 'php5-mcrypt' has no installation candidate
E: Package 'php5-sqlite' has no installation candidate
E: Unable to locate package php5-xdebug
E: Package 'php-apc' has no installation candidate
ERROR: Service 'front' failed to build: The command '/bin/sh -c apt-get update && apt-get install -my   supervisor   curl   wget   php5-curl   php5-fpm   php5-gd   php5-memcached   php5-mysql   php5-mcrypt   php5-sqlite   php5-xdebug   php-apc' returned a non-zero code: 100

**Comment by kasperisager** [comment]
`master` is failing with this exact same error as well (https://travis-ci.org/kasperisager/php-dockerized). I might be able to take a look at it this weekend, though I cannot promise anything. A PR would be most welcomed if someone has the time ❤️
