### ISSUE TITLE
Is there anyway to make this work in a docker swarm cluster

### ISSUE THREAD

**Issue by chillz561** [kasperisager/php-dockerized#60]
for example how can i run this as a service in swarm mode

**Comment by chillz561** [comment]
ok do you by any chance have any suggestions or resources that might have something that works for production use , i am  learning docker and wanting to utilize  nginx on some personal projects in
 a swarm cluster

**Comment by kasperisager** [comment]
My Google-foo led to the following: https://docs.docker.com/engine/swarm/services/
